name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

env:
  CI: true

jobs:
  lint:
    name: Lint on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - run: yarn install
    - name: Positive smoke test
      run: bin/plistlint test/fixtures/valid.plist
    - name: Negative smoke test
      run: (! bin/plistlint test/fixtures/invalid.plist)
