name: Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '**'

env:
  CI: true

jobs:
  lint:
    name: Lint on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - run: yarn install
